import { makeStyles } from '@material-ui/core/styles';

export default makeStyles((theme) => ({
    root: {
        width: '100%',
        height: '100%',
        paddingTop: '6%',
        padding: theme.spacing(4),
        display: 'inline-flex',
        justifyContent: 'center',
        margin: 0,
        flexGrow: 1,
    },
    leftContainer:{
        display: 'inline-flex',
        flexDirection: 'column',
    },
    container2: {
        display: 'inline-flex',
        justifyContent: 'flex-start',
        width: '75%',
        marginLeft: '8.2%',
        flexDirection: 'column',
    },
    tags:{
        width: 'fit-content',
        height: '25px',
        margin: '5px 10px 5px 0px',
        backgroundColor: '#7A431D',
        borderRadius: '15px',
        color: 'white',
        fontSize: 15
    },
    uploader: {
        height: '100%',
        marginLeft: '2%',
        display: 'inline-flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
    },
    contactUs:{
        width: '100px',
        height: '25px',
        margin: '5px 10px 5px 0px',
        backgroundColor: theme.palette.primary.main,
        borderRadius: '5px',
        textTransform: 'none',
        color: 'white',
        fontSize: 15
    },
    rightContainer: {
        display: 'inline-flex',
        justifyContent: 'center',
        alignContent: 'flex-start',
        alignItems: 'flex-start',
        position: 'fixed',
        width: '100vw',
        flexDirection: 'column',
        left: 900,
    },
    mainImageContainer: {
        width: '44.1em',
        height: '30em',
        minWidth: '100px',
        minHeight: '100px',
        margin: '0px 0px 0.8% 0px',
    },
    imagePreview: {
        width: '100%',
        height: '100%',
        borderRadius: '5px',
        objectFit: 'cover',
    },
    specs: {
        width:'80%',
        backgroundColor: 'white',
        border: `1px solid rgb(0,0,0,0.2)`,
        padding: '5%',
        display: 'inline-flex',
        flexDirection: 'column',
    },
    miniSpecs: {
        width: '100%',
        display: 'inline-flex',
        alignContent: 'center',
        alignItems: 'center',
        padding: '0.5em',
        justifyItems: 'center',
        justifyContent: 'space-between',
    },
    socials: {
        width: '100%',
        display: 'inline-flex',
        alignContent: 'center',
        alignItems: 'center',
        padding: '0.5em 0em 0em 0em',
        justifyItems: 'flex-start',
    },
    values:{
        width: '50%',
        display: 'inline-flex',
        alignContent: 'center',
        alignItems: 'center',
        justifyItems: 'center',
        justifyContent: 'space-between',
    },
    text:{
        color: 'black',
    },
    breadcrumb: {
        color: theme.palette.secondary.main,
        fontWeight: 300,
        paddingBottom: '1%',
        marginBottom: '1%',
        width: '30%',
        borderBottom: '1px solid black'
    },
    images: {
        width: '100%',
        height: '100%',
        borderRadius: '5px',
        paddingTop: '0px',
    },
    gridList: {
        width: '30%',
        height: '10%',
        display: 'inline-flex',
        flexWrap: 'wrap',
        padding: '0px 0px 0px 0px',
    },
    gridList2: {
        width: '100.40%',
        display: 'inline-flex',
        flexWrap: 'nowrap',
        transform: 'translateZ(0)',
        padding: '0px 0px 0px 0px',
        marginLeft: '10px',
        scrollbarWidth: 'thin',
    },
    price: {
        fontWeight: 600,
        fontSize: 28,
    },
    specTexts: {
        fontWeight: 300,
    },
    modal: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
      },
      modal2: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
      },
      modal3: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
      },
      paper: {
        backgroundColor: theme.palette.background.paper,
        border: '1px solid rgba(0,0,0,0.2)',
        boxShadow: theme.shadows[5],
        padding: theme.spacing(2, 4, 3),
        borderRadius: '5px',
        width: '50%',
      },
      paper2: {
        backgroundColor: theme.palette.background.paper,
        border: '1px solid rgba(0,0,0,0.2)',
        boxShadow: theme.shadows[5],
        padding: theme.spacing(2, 4, 3),
        borderRadius: '5px',
        width: '80%',
      },
      paper3: {
        backgroundColor: theme.palette.background.paper,
        border: '1px solid rgba(0,0,0,0.2)',
        boxShadow: theme.shadows[5],
        padding: theme.spacing(2, 4, 3),
        borderRadius: '5px',
        width: '50%',
      },
      inputLong: {
		backgroundColor: '#F3F3F4',
		display: 'inline-flex',
		alignItems: 'flex-start',
		border: 'none',
		zIndex: 1,
		height: '12rem',
		width: '100%',
		margin: '0.5rem 0rem 0.5rem 0rem',
	},
    submitButton: {
        width: '50%',
        marginTop: '15px',
        backgroundColor: theme.palette.primary.main,
        color: 'white',
        '&:hover': {
            backgroundColor: theme.palette.primary.secondary,
        }
    },
    submitButton2: {
        width: '100%',
        marginTop: '15px',
        backgroundColor: theme.palette.primary.main,
        color: 'white',
        '&:hover': {
            backgroundColor: theme.palette.primary.secondary,
        }
    },
    modalHeading: {
        display: 'inline-flex',
        justifyContent: 'space-between',
        width: '100%',
    },
    modalHeading2: {
        display: 'inline-flex',
        justifyContent: 'space-between',
        width: '100%',
        paddingBottom: '2%',
    },
    modalHeading3: {
        display: 'inline-flex',
        justifyContent: 'space-between',
        width: '80%',
        paddingBottom: '2%',
    },
    modalTitle: {
        color: '#372C2E',
        fontSize: 30,
    },
    input: {
		backgroundColor: '#F3F3F4',
		border: 'none',
		zIndex: 1,
		height: '36px',
		width: '100%',
		margin: '0.5rem 0rem 0.5rem 0rem',
	},
    fieldLabel: {
        fontWeight: 600,
        display: 'inline-flex',
        alignItems: 'center',

        alignContent: 'center',
    },
    inputBlock: {
        marginTop: '10%',
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        alignContent: 'center',
    },
    editButton: {
        textDecoration: 'none',
        color: 'white',
        backgroundColor: '#DE9E48',
        width: '80%',
        marginTop: '1em',
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        alignContent: 'center',
        paddingTop: '1em',
        paddingBottom: '1em',
        borderRadius: '4px',
    },
    saveButton: {
        textDecoration: 'none',
        color: 'black',
        border: '1px solid rgba(0,0,0,0.8)',
        backgroundColor: 'white',
        width: '100%',
        marginTop: '1em',
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        alignContent: 'center',
        paddingTop: '1em',
        paddingBottom: '1em',
        borderRadius: '4px',
    },
    cardContainer: {
        width: '200px',
        height: '200px',
        display: 'inline-flex',
        justifyContent: 'center',
        alignContent: 'center',
        alignItems: 'center',
    },
    imageContainer: {
        width: '190px',
        height: '190px',
        
    },
    backButton: {
        padding: 0, 
        marginLeft: '-5%',
        width: 'max-content', 
        '&:active': {background: 'none'},
        '&:hover': {background: 'none'},
    }
}));